export interface Inquirydetailinterface{
  MANDT: any
  VBELN: any
  POSNR: any
  MATNR: any
  MATWA: any
  PMATN: any
  CHARG: any
  MATKL: any
  ARKTX: any
  PSTYV: any
  POSAR: any
  LFREL: any
  FKREL: any
  UEPOS: any
  GRPOS: any
  ABGRU: any
  PRODH: any
  ZWERT: any
  ZMENG: any
  ZIEME: any
  UMZIZ: any
  UMZIN: any
  MEINS: any
  SMENG: any
  ABLFZ: any
  ABDAT: any
  ABSFZ: any
  POSEX: any
  KDMAT: any
  KBVER: any
  KEVER: any
  VKGRU: any
  VKAUS: any
  GRKOR: any
  FMENG: any
  UEBTK: any
  UEBTO: any
  UNTTO: any
  FAKSP: any
  ATPKZ: any
  RKFKF: any
  SPART: any
  GSBER: any
  NETWR: any
  WAERK: any
  ANTLF: any
  KZTLF: any
  CHSPL: any
  KWMENG: any
  LSMENG: any
  KBMENG: any
  KLMENG: any
  VRKME: any
  UMVKZ: any
  UMVKN: any
  BRGEW: any
  NTGEW: any
  GEWEI: any
  VOLUM: any
  VOLEH: any
  VBELV: any
  POSNV: any
  VGBEL: any
  VGPOS: any
  VOREF: any
  UPFLU: any
  ERLRE: any
  LPRIO: any
  WERKS: any
  LGORT: any
  VSTEL: any
  ROUTE: any
  STKEY: any
  STDAT: any
  STLNR: any
  STPOS: any
  AWAHR: any
  ERDAT: any
  ERNAM: any
  ERZET: any
  TAXM1: any
  TAXM2: any
  TAXM3: any
  TAXM4: any
  TAXM5: any
  TAXM6: any
  TAXM7: any
  TAXM8: any
  TAXM9: any
  VBEAF: any
  VBEAV: any
  VGREF: any
  NETPR: any
  KPEIN: any
  KMEIN: any
  SHKZG: any
  SKTOF: any
  MTVFP: any
  SUMBD: any
  KONDM: any
  KTGRM: any
  BONUS: any
  PROVG: any
  EANNR: any
  PRSOK: any
  BWTAR: any
  BWTEX: any
  XCHPF: any
  XCHAR: any
  LFMNG: any
  STAFO: any
  WAVWR: any
  KZWI1: any
  KZWI2: any
  KZWI3: any
  KZWI4: any
  KZWI5: any
  KZWI6: any
  STCUR: any
  AEDAT: any
  EAN11: any
  FIXMG: any
  PRCTR: any
  MVGR1: any
  MVGR2: any
  MVGR3: any
  MVGR4: any
  MVGR5: any
  KMPMG: any
  SUGRD: any
  SOBKZ: any
  VPZUO: any
  PAOBJNR: any
  PS_PSP_PNR: any
  AUFNR: any
  VPMAT: any
  VPWRK: any
  PRBME: any
  UMREF: any
  KNTTP: any
  KZVBR: any
  SERNR: any
  OBJNR: any
  ABGRS: any
  BEDAE: any
  CMPRE: any
  CMTFG: any
  CMPNT: any
  CMKUA: any
  CUOBJ: any
  CUOBJ_CH: any
  CEPOK: any
  KOUPD: any
  SERAIL: any
  ANZSN: any
  NACHL: any
  MAGRV: any
  MPROK: any
  VGTYP: any
  PROSA: any
  UEPVW: any
  KALNR: any
  KLVAR: any
  SPOSN: any
  KOWRR: any
  STADAT: any
  EXART: any
  PREFE: any
  KNUMH: any
  CLINT: any
  CHMVS: any
  STLTY: any
  STLKN: any
  STPOZ: any
  STMAN: any
  ZSCHL_K: any
  KALSM_K: any
  KALVAR: any
  KOSCH: any
  UPMAT: any
  UKONM: any
  MFRGR: any
  PLAVO: any
  KANNR: any
  CMPRE_FLT: any
  ABFOR: any
  ABGES: any
  J_1BCFOP: any
  J_1BTAXLW1: any
  J_1BTAXLW2: any
  J_1BTXSDC: any
  WKTNR: any
  WKTPS: any
  SKOPF: any
  KZBWS: any
  WGRU1: any
  WGRU2: any
  KNUMA_PI: any
  KNUMA_AG: any
  KZFME: any
  LSTANR: any
  TECHS: any
  MWSBP: any
  BERID: any
  PCTRF: any
  LOGSYS_EXT: any
  J_1BTAXLW3: any
  J_1BTAXLW4: any
  J_1BTAXLW5: any
  STOCKLOC: any
  SLOCTYPE: any
  MSR_RET_REASON: any
  MSR_REFUND_CODE: any
  MSR_APPROV_BLOCK: any
  NRAB_KNUMH: any
  TRMRISK_RELEVANT: any
  SGT_RCAT: any
  HANDOVERLOC: any
  HANDOVERDATE: any
  HANDOVERTIME: any
  TC_AUT_DET: any
  MANUAL_TC_REASON: any
  FISCAL_INCENTIVE: any
  TAX_SUBJECT_ST: any
  FISCAL_INCENTIVE_ID: any
  SPCSTO: any
  _DATAAGING: any
  REVACC_REFID: any
  REVACC_REFTYPE: any
  "_-BEV1_-SRFUND": any
  AUFPL_OLC: any
  APLZL_OLC: any
  FERC_IND: any
  FSH_SEASON_YEAR: any
  FSH_SEASON: any
  FSH_COLLECTION: any
  FSH_THEME: any
  FSH_CRSD: any
  FSH_SEAREF: any
  FSH_CANDATE: any
  FSH_PSM_PFM_SPLIT: any
  FSH_VAS_REL: any
  FSH_VAS_PRNT_ID: any
  FSH_TRANSACTION: any
  FSH_ITEM_GROUP: any
  FSH_ITEM: any
  FSH_VASREF: any
  FSH_GRID_COND_REC: any
  KOSTL: any
  FONDS: any
  FISTL: any
  FKBER: any
  GRANT_NBR: any
  BUDGET_PD: any
  IUID_RELEVANT: any
  MILL_SE_GPOSN: any
  PRS_OBJNR: any
  PRS_SD_SPSNR: any
  PRS_WORK_PERIOD: any
  TAS: any
  BETC: any
  MOD_ALLOW: any
  CANCEL_ALLOW: any
  PAY_METHOD: any
  BPN: any
  REP_FREQ: any
  FMFGUS_KEY: any
  PARGB: any
  AUFPL_OAA: any
  APLZL_OAA: any
  WRF_CHARSTC1: any
  WRF_CHARSTC2: any
  WRF_CHARSTC3: any
  ARSNUM: any
  ARSPOS: any
  WTYSC_CLMITEM: any
}
