export interface DELIVERYDETAILINTERFACE {
  MANDT: any
  VBELN: any
  POSNR: any
  PSTYV: any
  ERNAM: any
  ERZET: any
  ERDAT: any
  MATNR: any
  MATWA: any
  MATKL: any
  WERKS: any
  LGORT: any
  CHARG: any
  LICHN: any
  KDMAT: any
  PRODH: any
  LFIMG: any
  MEINS: any
  VRKME: any
  UMVKZ: any
  UMVKN: any
  NTGEW: any
  BRGEW: any
  GEWEI: any
  VOLUM: any
  VOLEH: any
  KZTLF: any
  UEBTK: any
  UEBTO: any
  UNTTO: any
  CHSPL: any
  FAKSP: any
  MBDAT: any
  LGMNG: any
  ARKTX: any
  LGPBE: any
  VBELV: any
  POSNV: any
  VBTYV: any
  VGSYS: any
  VGBEL: any
  VGPOS: any
  UPFLU: any
  UEPOS: any
  FKREL: any
  LADGR: any
  TRAGR: any
  KOMKZ: any
  LGNUM: any
  LISPL: any
  LGTYP: any
  LGPLA: any
  BWTEX: any
  BWART: any
  BWLVS: any
  KZDLG: any
  BDART: any
  PLART: any
  MTART: any
  XCHPF: any
  XCHAR: any
  VGREF: any
  POSAR: any
  BWTAR: any
  SUMBD: any
  MTVFP: any
  EANNR: any
  GSBER: any
  VKBUR: any
  VKGRP: any
  VTWEG: any
  SPART: any
  GRKOR: any
  FMENG: any
  ANTLF: any
  VBEAF: any
  VBEAV: any
  STAFO: any
  WAVWR: any
  KZWI1: any
  KZWI2: any
  KZWI3: any
  KZWI4: any
  KZWI5: any
  KZWI6: any
  SOBKZ: any
  AEDAT: any
  EAN11: any
  KVGR1: any
  KVGR2: any
  KVGR3: any
  KVGR4: any
  KVGR5: any
  MVGR1: any
  MVGR2: any
  MVGR3: any
  MVGR4: any
  MVGR5: any
  VPZUO: any
  VGTYP: any
  RFVGTYP: any
  KOSTL: any
  KOKRS: any
  PAOBJNR: any
  PRCTR: any
  PS_PSP_PNR: any
  AUFNR: any
  POSNR_PP: any
  KDAUF: any
  KDPOS: any
  VPMAT: any
  VPWRK: any
  PRBME: any
  UMREF: any
  KNTTP: any
  KZVBR: any
  FIPOS: any
  FISTL: any
  GEBER: any
  PCKPF: any
  BEDAR_LF: any
  CMPNT: any
  KCMENG: any
  KCBRGEW: any
  KCNTGEW: any
  KCVOLUM: any
  UECHA: any
  CUOBJ: any
  CUOBJ_CH: any
  ANZSN: any
  SERAIL: any
  KCGEWEI: any
  KCVOLEH: any
  SERNR: any
  ABRLI: any
  ABART: any
  ABRVW: any
  QPLOS: any
  QTLOS: any
  NACHL: any
  MAGRV: any
  OBJKO: any
  OBJPO: any
  AESKD: any
  SHKZG: any
  PROSA: any
  UEPVW: any
  EMPST: any
  ABTNR: any
  KOQUI: any
  STADAT: any
  AKTNR: any
  KNUMH_CH: any
  PREFE: any
  EXART: any
  CLINT: any
  CHMVS: any
  ABELN: any
  ABELP: any
  LFIMG_FLO: any
  LGMNG_FLO: any
  KCMENG_FLO: any
  KZUMW: any
  KMPMG: any
  AUREL: any
  KPEIN: any
  KMEIN: any
  NETPR: any
  NETWR: any
  KOWRR: any
  KZBEW: any
  MFRGR: any
  CHHPV: any
  ABFOR: any
  ABGES: any
  MBUHR: any
  WKTNR: any
  WKTPS: any
  J_1BCFOP: any
  J_1BTAXLW1: any
  J_1BTAXLW2: any
  J_1BTXSDC: any
  SITUA: any
  RSNUM: any
  RSPOS: any
  RSART: any
  KANNR: any
  KZFME: any
  PROFL: any
  KCMENGVME: any
  KCMENGVMEF: any
  KZBWS: any
  PSPNR: any
  EPRIO: any
  RULES: any
  KZBEF: any
  MPROF: any
  EMATN: any
  LGBZO: any
  HANDLE: any
  VERURPOS: any
  LIFEXPOS: any
  NOATP: any
  NOPCK: any
  RBLVS: any
  BERID: any
  BESTQ: any
  UMBSQ: any
  UMMAT: any
  UMWRK: any
  UMLGO: any
  UMCHA: any
  UMBAR: any
  UMSOK: any
  SONUM: any
  USONU: any
  AKKUR: any
  AKMNG: any
  VKGRU: any
  SHKZG_UM: any
  INSMK: any
  KZECH: any
  FLGWM: any
  BERKZ: any
  HUPOS: any
  NOWAB: any
  KONTO: any
  KZEAR: any
  HSDAT: any
  VFDAT: any
  LFGJA: any
  LFBNR: any
  LFPOS: any
  GRUND: any
  FOBWA: any
  DLVTP: any
  EXBWR: any
  BPMNG: any
  EXVKW: any
  CMPRE_FLT: any
  KZPOD: any
  LFDEZ: any
  UMREV: any
  PODREL: any
  KZUML: any
  FKBER: any
  GRANT_NBR: any
  KZWSO: any
  GMCONTROL: any
  POSTING_CHANGE: any
  UM_PS_PSP_PNR: any
  PRE_VL_ETENS: any
  SPE_GEN_ELIKZ: any
  SPE_SCRAP_IND: any
  SPE_AUTH_any: any
  SPE_INSPOUT_GUID: any
  SPE_FOLLOW_UP: any
  SPE_EXP_DATE_EXT: any
  SPE_EXP_DATE_INT: any
  SPE_AUTH_COMPLET: any
  ORMNG: any
  SPE_ATP_TMSTMP: any
  SPE_ORIG_SYS: any
  SPE_LIEFFZ: any
  SPE_IMWRK: any
  SPE_LIFEXPOS2: any
  SPE_EXCEPT_CODE: any
  SPE_KEEP_QTY: any
  SPE_ALTERNATE: any
  SPE_MAT_SUBST: any
  SPE_STRUC: any
  SPE_EXP_DATE_EXT_B: any
  STK_SEGMENT: any
  REQ_SEGMENT: any
  MATNR_LONG: any
  MATWA_LONG: any
  VPMAT_LONG: any
  EMATN_LONG: any
  UMMAT_LONG: any
  VBTYV_LONG: any
  VGTYP_LONG: any
  RFVGTYP_LONG: any
}
