export interface SALESORDERINTERFACE {
  SD_DOC: any
  ITM_NUMBER: string
  MATERIAL: string
  SHORT_TEXT: string
  DOC_TYPE: string
  DOC_DATE: string
  REQ_QTY: string
  REQ_DATE: string
  PURCH_NO: string
  BATCH: string
  VALID_FROM: string
  VALID_TO: string
  BILL_BLOCK: string
  DLV_BLOCK: string
  SOLD_TO: string
  NAME: string
  EXCHG_RATE: string
  DLV_QTY: number
  BASE_UOM: string
  NET_PRICE: string
  COND_P_UNT: number
  COND_UNIT: string
  NET_VAL_HD: string
  NET_VALUE: string
  DIVISION: string
  DOC_STATUS: string
  SALES_GRP: string
  SALES_OFF: string
  SALES_ORG: string
  SALES_UNIT: string
  SHIP_POINT: string
  DISTR_CHAN: string
  GI_DATE: string
  CURRENCY: string
  PLANT: string
  STORE_LOC: string
  ORD_REASON: string
  REASON_REJ: string
  B_UOM_ISO: string
  CD_UNT_ISO: string
  S_UNIT_ISO: string
  CURR_ISO: string
  PURCH_NO_C: string
  EXCHG_RATE_V: number
  MAT_EXT: string
  MAT_GUID: string
  MAT_VERS: string
  CREATION_DATE: string
  CREATION_TIME: string
  STATUS_DOC: string
  REQ_SEGMENT: string
  MATERIAL_LONG: string
}
