export interface INVOICEINTERFACE {
  MANDT: number
  VBELN: any
  FKART: string
  FKTYP: string
  VBTYP: string
  WAERK: string
  VKORG: string
  VTWEG: string
  KALSM: string
  KNUMV: string
  VSBED: string
  FKDAT: string
  BELNR: string
  GJAHR: string
  POPER: string
  KONDA: string
  KDGRP: string
  BZIRK: string
  PLTYP: string
  INCO1: string
  INCO2: string
  EXPKZ: string
  RFBSK: string
  MRNKZ: string
  KURRF: string
  CPKUR: string
  VALTG: string
  VALDT: string
  ZTERM: string
  ZLSCH: string
  KTGRD: string
  LAND1: string
  REGIO: string
  COUNC: string
  CITYC: string
  BUKRS: string
  TAXK1: number
  TAXK2: string
  TAXK3: string
  TAXK4: string
  TAXK5: string
  TAXK6: string
  TAXK7: string
  TAXK8: string
  TAXK9: string
  NETWR: string
  ZUKRI: string
  ERNAM: string
  ERZET: string
  ERDAT: string
  STAFO: string
  KUNRG: string
  KUNAG: string
  MABER: string
  STWAE: string
  EXNUM: string
  STCEG: string
  AEDAT: string
  SFAKN: string
  KNUMA: string
  FKART_RL: string
  FKDAT_RL: string
  KURST: string
  MSCHL: string
  MANSP: string
  SPART: string
  KKBER: string
  KNKLI: string
  CMWAE: string
  CMKUF: number
  HITYP_PR: string
  BSTNK_VF: string
  VBUND: string
  FKART_AB: string
  KAPPL: string
  LANDTX: string
  STCEG_H: string
  STCEG_L: string
  XBLNR: string
  ZUONR: string
  MWSBK: number
  LOGSYS: string
  FKSTO: string
  XEGDR: string
  RPLNR: string
  LCNUM: string
  J_1AFITP: string
  KURRF_DAT: string
  AKWAE: string
  AKKUR: number
  KIDNO: string
  BVTYP: string
  NUMPG: string
  BUPLA: string
  VKONT: string
  FKK_DOCSTAT: string
  NRZAS: string
  SPE_BILLING_IND: string
  VTREF: string
  FK_SOURCE_SYS: string
  FKTYP_CRM: string
  STGRD: string
  VBTYP_EXT: string
  J_1TPBUPL: string
  INCOV: string
  INCO2_L: string
  INCO3_L: string
  DPC_REL: string
  MNDID: string
  PAY_TYPE: string
  SEPON: string
  MNDVG: string
  SPPAYM: string
  SPPORD: string
}
