export interface INVOICEDETAILINTERFACE {
  MANDT: any
  VBELN: any
  POSNR: any
  UEPOS: any
  FKIMG: any
  VRKME: any
  UMVKZ: any
  UMVKN: any
  MEINS: any
  SMENG: any
  FKLMG: any
  LMENG: any
  NTGEW: any
  BRGEW: any
  GEWEI: any
  VOLUM: any
  VOLEH: any
  GSBER: any
  PRSDT: any
  FBUDA: any
  KURSK: any
  NETWR: any
  VBELV: any
  POSNV: any
  VGBEL: any
  VGPOS: any
  VGTYP: any
  AUBEL: any
  AUPOS: any
  AUREF: any
  MATNR: any
  ARKTX: any
  PMATN: any
  CHARG: any
  MATKL: any
  PSTYV: any
  POSAR: any
  PRODH: any
  VSTEL: any
  ATPKZ: any
  SPART: any
  POSPA: any
  WERKS: any
  ALAND: any
  WKREG: any
  WKCOU: any
  WKCTY: any
  TAXM1: any
  TAXM2: any
  TAXM3: any
  TAXM4: any
  TAXM5: any
  TAXM6: any
  TAXM7: any
  TAXM8: any
  TAXM9: any
  KOWRR: any
  PRSFD: any
  SKTOF: any
  SKFBP: any
  KONDM: any
  KTGRM: any
  KOSTL: any
  BONUS: any
  PROVG: any
  EANNR: any
  VKGRP: any
  VKBUR: any
  SPARA: any
  SHKZG: any
  ERNAM: any
  ERDAT: any
  ERZET: any
  BWTAR: any
  LGORT: any
  STAFO: any
  WAVWR: any
  KZWI1: any
  KZWI2: any
  KZWI3: any
  KZWI4: any
  KZWI5: any
  KZWI6: any
  STCUR: any
  UVPRS: any
  UVALL: any
  EAN11: any
  PRCTR: any
  KVGR1: any
  KVGR2: any
  KVGR3: any
  KVGR4: any
  KVGR5: any
  MVGR1: any
  MVGR2: any
  MVGR3: any
  MVGR4: any
  MVGR5: any
  MATWA: any
  BONBA: any
  KOKRS: any
  PAOBJNR: any
  PS_PSP_PNR: any
  AUFNR: any
  TXJCD: any
  CMPRE: any
  CMPNT: any
  CUOBJ: any
  CUOBJ_CH: any
  KOUPD: any
  UECHA: any
  XCHAR: any
  ABRVW: any
  SERNR: any
  BZIRK_AUFT: any
  KDGRP_AUFT: any
  KONDA_AUFT: any
  LLAND_AUFT: any
  MPROK: any
  PLTYP_AUFT: any
  REGIO_AUFT: any
  VKORG_AUFT: any
  VTWEG_AUFT: any
  ABRBG: any
  PROSA: any
  UEPVW: any
  AUTYP: any
  STADAT: any
  FPLNR: any
  FPLTR: any
  AKTNR: any
  KNUMA_PI: any
  KNUMA_AG: any
  PREFE: any
  MWSBP: any
  AUGRU_AUFT: any
  FAREG: any
  UPMAT: any
  UKONM: any
  CMPRE_FLT: any
  ABFOR: any
  ABGES: any
  J_1ARFZ: any
  J_1AREGIO: any
  J_1AGICD: any
  J_1ADTYP: any
  J_1ATXREL: any
  J_1BCFOP: any
  J_1BTAXLW1: any
  J_1BTAXLW2: any
  J_1BTXSDC: any
  BRTWR: any
  WKTNR: any
  WKTPS: any
  RPLNR: any
  KURSK_DAT: any
  WGRU1: any
  WGRU2: any
  KDKG1: any
  KDKG2: any
  KDKG3: any
  KDKG4: any
  KDKG5: any
  VKAUS: any
  J_1AINDXP: any
  J_1AIDATEP: any
  KZFME: any
  MWSKZ: any
  VERTT: any
  VERTN: any
  SGTXT: any
  DELCO: any
  BEMOT: any
  RRREL: any
  AKKUR: any
  WMINR: any
  VGBEL_EX: any
  VGPOS_EX: any
  LOGSYS: any
  VGTYP_EX: any
  J_1BTAXLW3: any
  J_1BTAXLW4: any
  J_1BTAXLW5: any
  MSR_ID: any
  MSR_REFUND_CODE: any
  MSR_RET_REASON: any
  NRAB_KNUMH: any
  NRAB_VALUE: any
  DISPUTE_CASE: any
  FUND_USAGE_ITEM: any
  FARR_RELTYPE: any
  CLAIMS_TAXATION: any
  KURRF_DAT_ORIG: any
  VGTYP_EXT: any
  SGT_RCAT: any
  SGT_SCAT: any
  AUFPL: any
  APLZL: any
  DPCNR: any
  DCPNR: any
  DPNRB: any
  PEROP_BEG: any
  PEROP_END: any
  FMFGUS_KEY: any
  FSH_SEASON_YEAR: any
  FSH_SEASON: any
  FSH_COLLECTION: any
  FSH_THEME: any
  FONDS: any
  FISTL: any
  FKBER: any
  GRANT_NBR: any
  BUDGET_PD: any
  PRS_WORK_PERIOD: any
  PPRCTR: any
  PARGB: any
  AUFPL_OAA: any
  APLZL_OAA: any
  CAMPAIGN: any
  COMPREAS: any
  WRF_CHARSTC1: any
  WRF_CHARSTC2: any
  WRF_CHARSTC3: any
}
