export interface INQUIRYLISTINTERFACE{
  MANDT: number
  VBELN: any
  ERDAT: string
  ERZET: string
  ERNAM: string
  ANGDT: string
  BNDDT: string
  AUDAT: string
  VBTYP: string
  TRVOG: number
  AUART: string
  AUGRU: string
  GWLDT: string
  SUBMI: string
  LIFSK: string
  FAKSK: string
  NETWR: string
  WAERK: string
  VKORG: string
  VTWEG: string
  SPART: string
  VKGRP: string
  VKBUR: string
  GSBER: string
  GSKST: string
  GUEBG: string
  GUEEN: string
  KNUMV: string
  VDATU: string
  VPRGR: number
  AUTLF: string
  VBKLA: string
  VBKLT: string
  KALSM: string
  VSBED: string
  FKARA: string
  AWAHR: string
  KTEXT: string
  BSTNK: string
  BSARK: string
  BSTDK: string
  BSTZD: string
  IHREZ: string
  BNAME: string
  TELF1: string
  MAHZA: number
  MAHDT: string
  KUNNR: string
  KOSTL: string
  STAFO: string
  STWAE: string
  AEDAT: string
  KVGR1: string
  KVGR2: string
  KVGR3: string
  KVGR4: string
  KVGR5: string
  KNUMA: string
  KOKRS: string
  PS_PSP_PNR: string
  KURST: string
  KKBER: string
  KNKLI: string
  GRUPP: string
  SBGRP: string
  CTLPC: string
  CMWAE: string
  CMFRE: string
  CMNUP: string
  CMNGV: string
  AMTBL: number
  HITYP_PR: string
  ABRVW: string
  ABDIS: string
  VGBEL: string
  OBJNR: string
  BUKRS_VF: string
  TAXK1: number
  TAXK2: string
  TAXK3: string
  TAXK4: string
  TAXK5: string
  TAXK6: string
  TAXK7: string
  TAXK8: string
  TAXK9: string
  XBLNR: string
  ZUONR: string
  VGTYP: string
  KALSM_CH: string
  AGRZR: string
  AUFNR: string
  QMNUM: string
  VBELN_GRP: string
  SCHEME_GRP: string
  ABRUF_PART: string
  ABHOD: string
  ABHOV: string
  ABHOB: string
  RPLNR: string
  VZEIT: string
  STCEG_L: string
  LANDTX: string
  XEGDR: string
  ENQUEUE_GRP: string
  DAT_FZAU: string
  FMBDAT: string
  VSNMR_V: string
  HANDLE: string
  PROLI: string
  CONT_DG: string
  CRM_GUID: string
  UPD_TMSTMP: number
  MSR_ID: string
  TM_CTRL_KEY: string
  HANDOVERLOC: string
  _DATAAGING: string
  PSM_BUDAT: string
  FSH_KVGR6: string
  FSH_KVGR7: string
  FSH_KVGR8: string
  FSH_KVGR9: string
  FSH_KVGR10: string
  FSH_REREG: string
  FSH_CQ_CHECK: string
  FSH_VRSN_STATUS: string
  FSH_TRANSACTION: string
  FSH_VAS_CG: string
  FSH_CANDATE: string
  FSH_SS: string
  FSH_OS_STG_CHANGE: string
  SWENR: string
  SMENR: string
  PHASE: string
  MTLAUR: string
  STAGE: number
  HB_CONT_REASON: string
  HB_EXPDATE: string
  HB_RESDATE: string
  MILL_APPL_ID: string
  TAS: string
  BETC: string
  MOD_ALLOW: string
  CANCEL_ALLOW: string
  PAY_METHOD: string
  BPN: string
  REP_FREQ: string
  LOGSYSB: string
  KALCD: string
  MULTI: string
  SPPAYM: string
  WTYSC_CLM_HDR: string
}
